[package]
name = "smn_server_get"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1"
aws-credential-types = "1.2.9"
aws-sdk-s3 = "1"
aws-types = "1.3.10"
axum = "0.8.7"
tokio = { version = "1", features = ["full"] }
